version: "3.3"
   
services:

  him:
    build: .
    container_name: him
    hostname: him
    volumes:
      - .:/him
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - him_db

  him_db:
    image: postgres:14.5
    container_name: him_db
    hostname: him_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: him
      POSTGRES_USER: him
      POSTGRES_PASSWORD: him
