#######################################################################
# NOTE: For a reason I don't understand, the gcloud command line tool #
# takes the _DATABASE_NAME as service argument for cloud_sql_proxy.   #
# I just don't get it...                                              #
#######################################################################

steps:  
  - id: "Apply Migrations: -> "
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i", "${_REGISTERY_URL}",
        "-s", "${_PROJECT_ID}:${_REGION}:${_DATABASE_NAME}",
        "-e", "SETTINGS_NAME=django_settings-${_GCP_ENV}",
        "--",
        "python",
        "manage.py",
        "migrate",
      ]

  - id: "Collectstatic: -> "
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i", "${_REGISTERY_URL}",
        "-s", "${_PROJECT_ID}:${_REGION}:${_DATABASE_NAME}",
        "-e", "SETTINGS_NAME=django_settings-${_GCP_ENV}",
        "--",
        "python",
        "manage.py",
        "collectstatic",
        "--verbosity",
        "2",
        "--no-input",
      ]

  - id: "Deploy container: -> "
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "him-api-${_GCP_ENV}",
        "--image=${_REGISTERY_URL}",
        "--port=${_PORT}",
        "--region=${_REGION}",
        "--platform=managed",
      ]

options:
  dynamic_substitutions: true

substitutions:
  _PROJECT_ID: him
  _DATABASE_NAME: him-${_GCP_ENV}
  _REGION: europe-west3
  _REGISTERY_URL: europe-west3-docker.pkg.dev/tinder-him/him/him-api
  _PORT: "8000"