# Generated by Django 4.1.3 on 2022-11-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personn',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('gender', models.IntegerField()),
                ('bio', models.TextField(null=True)),
                ('distance_mi', models.IntegerField(null=True)),
                ('birth_date', models.DateTimeField(null=True)),
                ('liked', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'personn',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.TextField()),
                ('score', models.FloatField(null=True)),
                ('personn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personn')),
            ],
            options={
                'db_table': 'photo',
                'ordering': ['created_at'],
            },
        ),
    ]
