# Generated by Django 4.1.3 on 2022-11-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_message_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="liked",
            field=models.BooleanField(default=True),
        ),
    ]
