# Generated by Django 4.1.3 on 2022-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_messagetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetemplate",
            name="nb_reply",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="nb_sent",
            field=models.IntegerField(null=True),
        ),
    ]
