# Generated by Django 4.1.3 on 2022-12-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_messagetemplate_nb_reply_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="match",
            field=models.BooleanField(default=False),
        ),
    ]
