# Generated by Django 4.1.3 on 2022-12-05 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_person_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('closed', models.BooleanField(default=False)),
                ('common_like_count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(null=True)),
                ('dead', models.BooleanField(default=False)),
                ('last_activity_date', models.DateTimeField(null=True)),
                ('message_count', models.IntegerField(default=0)),
                ('pending', models.BooleanField(default=False)),
                ('is_super_like', models.BooleanField(default=False)),
                ('is_boost_match', models.BooleanField(default=False)),
                ('is_super_boost_match', models.BooleanField(default=False)),
                ('is_primetime_boost_match', models.BooleanField(default=False)),
                ('is_experiences_match', models.BooleanField(default=False)),
                ('is_fast_match', models.BooleanField(default=False)),
                ('is_preferences_match', models.BooleanField(default=False)),
                ('is_matchmaker_match', models.BooleanField(default=False)),
                ('is_opener', models.BooleanField(default=False)),
                ('has_shown_initial_interest', models.BooleanField(default=False)),
                ('following', models.BooleanField(default=False)),
                ('following_moments', models.BooleanField(default=False)),
                ('subscription_tier', models.TextField(default='platinum')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_1', to='app.person')),
                ('person_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_2', to='app.person')),
            ],
            options={
                'db_table': 'match',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='app.match'),
        ),
    ]
