# Generated by Django 4.1.3 on 2022-12-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_match_message_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='subscription_tier',
            field=models.TextField(default='platinum', null=True),
        ),
    ]
