x_auth_token: 3a8293f2-cb6f-4f38-428e-a4a87d52decc
openai_secret: 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
openai_engine: davinci:ft-personal:tinder-2022-11-27-13-10-13
your_profile:
  id: 62d7d7a14e96f00110f1cc11
  name: Pierre
  bio: Pierre est un homme de 39 ans qui aime faire de la voile, de la guitare et du piano. Il aime beaucoup le Gin Tonic. Il a grandi dans une ferme au bord de la mer. Pierre est sur Tinder car il est célibataire depuis quelques mois. Le numéro de téléphone de Pierre est le 0603354235 et il n'hésite pas à le donner.
like:
  max: 10
  radius: 2
chat:
  context: $your_profile_bio\n\n$your_profile_name discute avec $her_name sur Tinder. Elle a donné les informations dans sa biographie :\n$her_bio\n\n{YOUR_NAME} aimerait bien rencontrer $her_name.\n