steps:  
  - id: "Create User: -> "
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i", "${_REGISTERY_URL}",
        "-s", "${_PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e", "SETTINGS_NAME=django_settings-${_GCP_ENV}",
        "--",
        "python",
        "manage.py",
        "createjwtuser",
        "--name=${_USER_NAME}",
        "--email=${_USER_EMAIL}",
        "--password=${_USER_PASSWORD}"
      ]

options:
  dynamic_substitutions: true

substitutions:
  _PROJECT_ID: tinder-him
  _INSTANCE_NAME: him-${_GCP_ENV} # If you put him-api-${_GCP_ENV} (the Cloud Run Name), it will fail
  _REGION: europe-west3
  _REGISTERY_URL: europe-west3-docker.pkg.dev/tinder-him/him/him-api